// lib/seed/data.ts - Complete seed data for IMARAT IT Support
export const seedUsers = [
  {
    id: 'usr_admin_001',
    name: 'Ali Raza',
    email: 'aleeraza665@gmail.com',
    password: 'Securesocketshell@22', // Will be hashed
    role: 'MANAGER',
    department: 'IT Management',
    skills: ['management', 'network', 'security'],
    maxChats: 10,
    status: 'ONLINE',
    avatar: 'AR',
  },
  {
    id: 'usr_agent_001',
    name: 'Sarah Chen',
    email: 'sarah.chen@imarat.com',
    password: 'Agent@2024!',
    role: 'AGENT',
    department: 'IT Helpdesk',
    skills: ['hardware', 'network', 'software', 'vpn'],
    maxChats: 5,
    status: 'ONLINE',
    avatar: 'SC',
  },
  {
    id: 'usr_agent_002',
    name: 'James Okafor',
    email: 'james.okafor@imarat.com',
    password: 'Agent@2024!',
    role: 'AGENT',
    department: 'IT Helpdesk',
    skills: ['software', 'email', 'microsoft365', 'vpn'],
    maxChats: 5,
    status: 'BUSY',
    avatar: 'JO',
  },
  {
    id: 'usr_agent_003',
    name: 'Priya Nair',
    email: 'priya.nair@imarat.com',
    password: 'Agent@2024!',
    role: 'AGENT',
    department: 'IT Helpdesk',
    skills: ['hardware', 'printer', 'vpn', 'security'],
    maxChats: 4,
    status: 'AWAY',
    avatar: 'PN',
  },
  {
    id: 'usr_user_001',
    name: 'Tom Bradley',
    email: 'tom.bradley@imarat.com',
    password: 'User@2024!',
    role: 'USER',
    department: 'Finance',
    skills: [],
    maxChats: 1,
    status: 'ONLINE',
    avatar: 'TB',
  },
  {
    id: 'usr_user_002',
    name: 'Maya Singh',
    email: 'maya.singh@imarat.com',
    password: 'User@2024!',
    role: 'USER',
    department: 'Marketing',
    skills: [],
    maxChats: 1,
    status: 'ONLINE',
    avatar: 'MS',
  },
  {
    id: 'usr_user_003',
    name: 'David Park',
    email: 'david.park@imarat.com',
    password: 'User@2024!',
    role: 'USER',
    department: 'Operations',
    skills: [],
    maxChats: 1,
    status: 'OFFLINE',
    avatar: 'DP',
  },
]

export const seedKBArticles = [
  {
    title: 'How to Connect to Company VPN (Cisco AnyConnect)',
    category: 'Network',
    tags: ['vpn', 'remote', 'network', 'cisco'],
    content: `## Overview\nThis guide walks you through connecting to the IMARAT corporate VPN using Cisco AnyConnect.\n\n## Prerequisites\n- VPN client installed (contact IT if not installed)\n- Active company credentials\n- Internet connection\n- MFA device registered\n\n## Connection Steps\n1. Open Cisco AnyConnect from your system tray or applications menu\n2. Enter the VPN gateway: vpn.imarat.com\n3. Click Connect\n4. Enter username: IMARAT\\\\your.name (e.g., IMARAT\\\\tom.bradley)\n5. Enter your Active Directory password\n6. Approve the MFA push notification on your registered device\n\n## Common Errors\n**Error 691 - Authentication Failed**\nVerify your username includes the IMARAT\\\\ prefix. Check caps lock.\n\n**Error 442 - Client Version Mismatch**\nUpdate Cisco AnyConnect via Software Center or contact IT.\n\n**Connection Timeout**\nCheck your internet connection. Try a different network if on public Wi-Fi.\n\n## Still Having Issues?\nContact IT Helpdesk via live chat or raise a ticket with category Network/VPN.`,
    views: 847,
    helpful: 73,
    published: true,
  },
  {
    title: 'Setting Up Email Signature in Outlook 2021 / M365',
    category: 'Software',
    tags: ['outlook', 'email', 'signature', 'microsoft365'],
    content: `## Overview\nProfessional email signatures are mandatory for all IMARAT staff.\n\n## Desktop App (Outlook 2021)\n1. Open Outlook and navigate to File > Options > Mail\n2. Click Signatures in the Compose Messages section\n3. Select New and name your signature (e.g., "IMARAT Official")\n4. Use the IMARAT signature template at: \\\\\\\\fileserver\\\\IT\\\\Templates\\\\signature.html\n5. Set as default for New Messages and Replies/Forwards\n\n## Outlook Web App (OWA)\n1. Click the gear icon in the top right\n2. Select View All Outlook Settings\n3. Navigate to Mail > Compose and Reply\n4. Paste your HTML signature in the Email Signature field\n\n## Troubleshooting\n**Signature Appears as Attachment**\nThis occurs when images are embedded rather than linked. Use only the approved template which uses external image links.\n\n**Signature Missing on Mobile**\nConfigure separately in the Outlook mobile app under Settings > Signature.`,
    views: 412,
    helpful: 38,
    published: true,
  },
  {
    title: 'Resetting Your Active Directory / Microsoft 365 Password',
    category: 'Security',
    tags: ['password', 'active-directory', 'security', 'self-service'],
    content: `## Password Reset Methods\n\n## Method 1: Self-Service Password Reset Portal (Preferred)\n1. Visit: https://sspr.imarat.com\n2. Enter your username or registered email\n3. Complete MFA verification via SMS or Authenticator app\n4. Set your new password meeting all policy requirements\n5. Your password will sync to all IMARAT systems within 5 minutes\n\n## Method 2: IT Helpdesk (If self-service fails)\n1. Contact IT Helpdesk via live chat during business hours\n2. You must verify your identity with your employee ID and manager name\n3. A temporary password will be issued\n4. You must change it on first login\n\n## Password Policy\n- Minimum 12 characters\n- Must include: uppercase, lowercase, number, and special character\n- Cannot reuse last 12 passwords\n- Expires every 90 days\n- Account locks after 5 failed attempts\n\n## Best Practices\n- Use a password manager (LastPass or 1Password are approved)\n- Never share your password with colleagues or IT staff\n- Report suspected compromise immediately`,
    views: 1203,
    helpful: 98,
    published: true,
  },
  {
    title: 'Requesting New Hardware or Software',
    category: 'Procurement',
    tags: ['hardware', 'software', 'procurement', 'request', 'approval'],
    content: `## Procurement Process\n\nAll hardware and software must go through formal IT procurement to ensure licensing compliance and security standards.\n\n## How to Submit a Request\n1. Create a support ticket with category set to "Procurement"\n2. Include the following information:\n   - Item name, model/version, and specifications\n   - Vendor and estimated cost\n   - Business justification (why is this needed?)\n   - Required by date\n3. CC your line manager when submitting\n4. Your manager must approve before IT can proceed\n\n## Approval Timeline\n- Approved catalog items: 3-5 business days\n- Non-standard items: 10-15 business days (requires budget approval)\n- Emergency requests: Same day (requires Director-level sign-off)\n\n## Pre-Approved Hardware Catalog\nVisit the IMARAT IT Portal to browse items available for immediate order:\n- Standard laptops (Dell Latitude, MacBook Pro)\n- Monitors (24" and 27" options)\n- Peripherals (keyboards, mice, headsets)\n- Mobile devices (iPhone, Android options)\n\n## Software Licensing\nAll software must be on the approved list. Using unlicensed software is a disciplinary matter.`,
    views: 289,
    helpful: 25,
    published: true,
  },
  {
    title: 'Multi-Factor Authentication (MFA) Setup and Troubleshooting',
    category: 'Security',
    tags: ['mfa', 'security', '2fa', 'authenticator', 'microsoft'],
    content: `## Why MFA is Required\nMFA is mandatory for all IMARAT accounts. It provides a critical second layer of security against phishing and credential theft.\n\n## Initial Setup (Microsoft Authenticator - Recommended)\n1. Download Microsoft Authenticator from your device's app store\n2. On your computer, visit: https://aka.ms/mysecurityinfo\n3. Sign in with your IMARAT credentials\n4. Click Add Method and select Authenticator App\n5. Click Next and scan the displayed QR code with the app\n6. Enter the 6-digit code shown in the app to verify\n\n## Alternative Methods\n- **SMS**: Receive codes via text (less secure, use as backup only)\n- **Phone Call**: Receive automated voice call\n\n## Getting a New Phone\nRegister your new device BEFORE resetting or removing the old one.\n1. While still on old device, visit https://aka.ms/mysecurityinfo\n2. Add new device following setup steps above\n3. Remove old device after confirming new one works\n\n## Emergency Access\nIf you lose your MFA device and cannot sign in, contact IT Helpdesk immediately with your employee ID for emergency bypass code.`,
    views: 934,
    helpful: 81,
    published: true,
  },
  {
    title: 'Printer Setup and Troubleshooting Guide',
    category: 'Hardware',
    tags: ['printer', 'hardware', 'drivers', 'network-printer'],
    content: `## Adding a Network Printer\n\n## Windows\n1. Open Settings > Bluetooth and Devices > Printers and Scanners\n2. Click Add Device\n3. If the printer is not found automatically, click Add Manually\n4. Select Add a printer using TCP/IP address\n5. Enter the printer IP (see the printer list below or contact IT)\n\n## Floor-by-Floor Printer IPs\n- Ground Floor: 10.1.1.50 (HP LaserJet Pro)\n- 1st Floor: 10.1.2.50 (HP LaserJet Pro)\n- 2nd Floor: 10.1.3.50 (HP Color LaserJet)\n- 3rd Floor: 10.1.4.50 (HP LaserJet Pro)\n- Executive Floor: 10.1.5.50 (HP LaserJet Enterprise)\n\n## Common Issues\n**Printer Not Found**\n- Ensure you are connected to the office network (not Guest Wi-Fi)\n- Restart the print spooler: Run services.msc > Print Spooler > Restart\n\n**Printer Offline**\n- Check the physical printer is powered on and has paper\n- Cancel all pending jobs and try again\n- Re-add the printer using the steps above\n\n**Poor Print Quality**\n- Run the printer's self-cleaning function from its display panel\n- Contact IT if toner replacement is needed`,
    views: 367,
    helpful: 31,
    published: true,
  },
  {
    title: 'Working from Home: IT Setup Checklist',
    category: 'Remote Work',
    tags: ['remote-work', 'wfh', 'vpn', 'home-office', 'setup'],
    content: `## IMARAT Remote Work IT Requirements\n\nAll employees working from home must meet the following IT standards.\n\n## Required Setup\n- [ ] Company-issued laptop (personal devices require IT approval)\n- [ ] Cisco AnyConnect VPN installed and working\n- [ ] Microsoft 365 apps installed and licensed\n- [ ] Microsoft Authenticator configured on mobile device\n- [ ] Company email configured in Outlook\n- [ ] Microsoft Teams installed\n- [ ] Approved headset for video calls\n\n## Network Requirements\n- Minimum 25 Mbps download / 5 Mbps upload for standard work\n- Minimum 50 Mbps download / 10 Mbps upload for video-intensive roles\n- Use a wired ethernet connection where possible for stability\n\n## Security Requirements\n- Enable full-disk encryption (BitLocker on Windows, FileVault on Mac)\n- Keep your OS and software updated\n- Do not connect company devices to public Wi-Fi without VPN active\n- Lock your screen when stepping away (Win+L on Windows)\n\n## Getting IT Support Remotely\nAll IT support can be accessed through this portal. Agents can also perform remote desktop sessions using approved tools.`,
    views: 521,
    helpful: 47,
    published: true,
  },
]

export const seedQuickReplies = [
  {
    title: 'Greeting',
    text: 'Hello! Thank you for contacting IMARAT IT Support. I am here to help. Could you please describe the issue you are experiencing in as much detail as possible?',
    category: 'general',
  },
  {
    title: 'Request More Information',
    text: 'To help diagnose this issue effectively, could you please provide the following: 1) Your device name and model, 2) Operating system version, 3) Any error messages or codes you have seen, and 4) When the issue first started?',
    category: 'general',
  },
  {
    title: 'Remote Session Offer',
    text: 'I would like to remotely connect to your device to investigate this further. I will send you a connection link via email. Please accept the connection request when it arrives. The session is fully secure and I will only access files with your permission.',
    category: 'general',
  },
  {
    title: 'Resolution Check',
    text: 'I believe the issue should now be resolved. Could you please verify that everything is working correctly on your end? If the problem persists, please let me know and I will continue to assist.',
    category: 'general',
  },
  {
    title: 'Closing Message',
    text: 'I am glad I could help resolve your issue today. If this problem recurs or you need any further assistance, please do not hesitate to start a new chat or create a support ticket. Have a great day!',
    category: 'general',
  },
  {
    title: 'VPN - Domain Prefix',
    text: 'For VPN authentication, your username must include the domain prefix. Please use the format IMARAT\\\\your.name (for example: IMARAT\\\\tom.bradley). The double backslash is required.',
    category: 'network',
  },
  {
    title: 'Password Reset Link',
    text: 'You can reset your IMARAT password using our self-service portal at https://sspr.imarat.com. You will need to verify your identity via SMS or the Microsoft Authenticator app. Let me know if you encounter any issues.',
    category: 'security',
  },
  {
    title: 'Escalating to Ticket',
    text: 'I am converting this chat into a support ticket so our specialist team can investigate further. You will receive email updates and can track progress through the IT portal. Your ticket reference number will be sent shortly.',
    category: 'general',
  },
  {
    title: 'Software Center',
    text: 'For software installations, please use the IMARAT Software Center on your device. Open it from the Start Menu and search for the application you need. Most approved software can be installed without admin rights.',
    category: 'software',
  },
  {
    title: 'Out of Office / After Hours',
    text: 'Our standard support hours are Monday to Friday, 8:00 AM to 6:00 PM PKT. For critical issues outside these hours, please call the emergency IT line at +92-21-XXXX-XXXX. Non-urgent issues will be handled the next business day.',
    category: 'general',
  },
]

export const seedSystemSettings = [
  { key: 'company_name', value: 'IMARAT Corporation' },
  { key: 'support_email', value: 'itsupport@imarat.com' },
  { key: 'support_phone', value: '+92-21-XXXX-XXXX' },
  { key: 'timezone', value: 'Asia/Karachi' },
  { key: 'business_hours_start', value: '08:00' },
  { key: 'business_hours_end', value: '18:00' },
  { key: 'chat_auto_assign', value: 'true' },
  { key: 'chat_routing_strategy', value: 'round-robin' },
  { key: 'chat_idle_timeout', value: '300' },
  { key: 'chat_max_queue', value: '50' },
  { key: 'sla_critical_response', value: '0.5' },
  { key: 'sla_critical_resolution', value: '2' },
  { key: 'sla_high_response', value: '1' },
  { key: 'sla_high_resolution', value: '4' },
  { key: 'sla_medium_response', value: '2' },
  { key: 'sla_medium_resolution', value: '8' },
  { key: 'sla_low_response', value: '4' },
  { key: 'sla_low_resolution', value: '24' },
  { key: 'email_notifications', value: 'true' },
  { key: 'browser_notifications', value: 'true' },
  { key: 'ai_suggestions', value: 'true' },
]
